 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  machine:
    services:
      -docker
 jobs:
   build:
     executor: win/default
     steps:
       - checkout
       - run: dotnet test
       - run: echo $apirest
       - run: ssh -i "$apirest" ubuntu@ec2-54-191-24-157.us-west-2.compute.amazonaws.com
       - run: sh commands/Linux.sh
          
      
      

