 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  machine:
    services:
      -docker
 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: cd ./api-rest
       - run: docker build . -t artefacto
          
      
      

