 version: 2

 orbs:
  win: circleci/windows@2.2.0
  machine:
    services:
      -docker
  jobs:
    build:
      executor: win/default
      steps:
        - checkout
        - run: dotnet test
            
        
      

