 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  machine:
    services:
      -docker
  jobs:
    build:
      executor: win/default
      steps:
        - checkout
        - run: dotnet test
    deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "sh api-rest/desplegar.sh"
            
        
      

