version: 2

jobs:
    build:
      executor: win/default
      steps:
        - checkout
        - run: dotnet test
    deploy:
      machine:
        enabled: true
      steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
workflows:
   version: 2
   build-and-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only deploy once build job has completed
           filters:
             branches:
               only: master # only deploy on the master branch