name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hello world action
      env: # Or as an environment variable
        key: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_USER: "hola"
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      run: |
        echo $DEPLOY_USER
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: testsecrets
      run: echo  ${{ secrets.DEPLOY_USER }}
    - name: setpublickey
      run: echo -e $key> key
    - name: Deploy
      run: ssh -i "key" -o StrictHostKeyChecking=yes $DEPLOY_USER@$DEPLOY_HOST "sh api-rest/desplegar.sh"
