name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: build
      env: # Or as an environment variable
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: |
        sh api-rest/build.sh
    - name: Deploy
      env: # Or as an environment variable
        key: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: |
        sh api-rest/deploy.sh
